apiVersion: certmanager.k8s.io/v1beta1
kind: Certificate
metadata:
  name: wecodethis-tk-tls
spec:
  secretName: wecodethis-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wecodethis.tk
  dnsNames:
    - wecodethis.tk
    - www.wecodethis.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - wecodethis.tk
          - www.wecodethis.tk